[pytest]
testpaths = .
python_files = *.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: Smoke tests
    login: Login feature tests
    alert: Alert feature tests
    dropdown: Dropdown feature tests
    upload: File upload feature tests
    comment: Comment feature tests
    window: Multi-window feature tests
