[pytest]
testpaths = tests_py
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: Smoke tests
    tabs: Tab feature tests
    iframe: iFrame tests
    task: Task table tests
    progress: Progress bar tests
    notify: Notification tests
    countdown: Countdown tests
